// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"hm-dianping-go-zero/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/blog",
				Handler: saveBlogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/blog/hot",
				Handler: queryHotBlogHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/blog/like/:id",
				Handler: likeBlogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/blog/of/me",
				Handler: queryMyBlogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/test/refresh",
				Handler: testRefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/test/refresh-login",
				Handler: testRefreshTokenWithLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/code",
				Handler: sendCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/me",
				Handler: queryMyInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/voucher",
				Handler: addVoucherHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/voucher-order/seckill/:id",
				Handler: seckillVoucherHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/voucher/list/:shop_id",
				Handler: queryVoucherOfShopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/voucher/seckill",
				Handler: addSeckillVoucherHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
